import React, { createElement } from 'react'
import ReactDOM from 'react-dom'
// import App from '../src/pages/about'
// import App from '../src/pages/home'
// import App from '../src/pages/shadow'
// import App from '../src/pages/module'
// import App from '../src/pages/three/start'
// import App from '../src/pages/three/drawLine'
// import App from '../src/pages/three/drawText'
// import App from '../src/pages/three/addModel'
// import App from '../src/pages/three/light/physical'
// import App from '../src/pages/three/light/pointlights'
// import App from '../src/pages/typeScript/variable'
// import App from '../src/pages/typeScript/interface'
// import App from '../src/pages/typeScript/const+let'
// import App from '../src/pages/typeScript/class'
// import App from '../src/pages/typeScript/function'
// import App from '../src/pages/typeScript/generic'
// import App from '../src/pages/typeScript/enum'
// import App from '../src/pages/typeScript/type'
// import App from '../src/pages/typeScript/advanceType'
// import App from '../src/pages/proComponent/proTable'
import App from '../src/pages/activity'

const root = document.querySelector('#root')

ReactDOM.render(createElement(App), root)
