export default {
  headUrl: 'https://myitsky.com/%E5%A4%B4%E5%9B%BE.png',
  hasAnimation: true,
  animationImageUrl: 'xxxx',
  layoutInfo: {
    id: 2,
    name: 'xxx',
    materials: [
      {
        id: 1,
        sort: 1,
        name: '生日庆典',
        type: 'STATIC',
        background_image: 'https://myitsky.com/material.png',
        height: 200,
        marginTop: 80,
        marginBottom: 20,
      },
      {
        id: 2,
        sort: 2,
        name: '优惠券',
        type: 'COUPON',
        height: 200,
        marginTop: 10,
        marginBottom: 10,
      },
      {
        id: 3,
        sort: 3,
        name: '抽奖',
        type: 'LUCK',
        height: 200,
        marginTop: 40,
        marginBottom: 10,
      },
      {
        id: 4,
        sort: 4,
        name: '生日庆典',
        type: 'STATIC',
        background_image: 'https://myitsky.com/material.png',
        height: 200,
        marginTop: 10,
        marginBottom: 10,
      },
    ],
  },
}
